### ISSUE TITLE
List non-core Perl module dependencies

### ISSUE THREAD

**Issue by tseemann** [SionBayliss/PIRATE#18]
Some modules are core, but it depend on perl version. Let's say 5.26:
https://perldoc.perl.org/5.26.0/index-modules-T.html

These are the modules you are using:
```
grep -h '^use ' -r . | cut -d ' ' -f2 | sed 's/;//' | sort | uniq -c | sort -nr
     43 warnings
     43 strict
     29 Getopt::Long
     28 Pod::Usage
     20 File::Basename
     20 Cwd
      3 Text::Wrap
      3 List::Util
      2 Bio::AlignIO
      1 IPC::Open2
      1 File::Temp
      1 Bio::SeqIO
      1 Bio::Seq
      1 Bio::Perl
```

The good news is, I think Bioperl is the only non-core Perl module!

**Comment by SionBayliss** [comment]
In a future version of PIRATE I will remove the dependency on bioperl. It think it is only used for parsing fasta files and translation. The dependency on bioperl is included in the README. Would you recommend mentioning the core dependencies anywhere?

**Comment by tseemann** [comment]
To clarify, you have done everything right. No need to list core modules. 
Avoiding Bioperl would make it easier to install in some cases, but ultimately brew and conda take care og it all.
