### ISSUE TITLE
bioconda recipe in progress

### ISSUE THREAD

**Issue by tseemann** [SionBayliss/PIRATE#26]
See https://github.com/bioconda/bioconda-recipes/pull/17798

**Comment by SionBayliss** [comment]
Great! Shall I wait for your PR before dealing with the most recent issues that you have raised? Or should I address the xargs and exit 0 --checks fixes?

**Comment by tseemann** [comment]
Someone accepted the PR despite the bug... maybe you can try it and see if it works?

**Comment by SionBayliss** [comment]
The main functionality works but the plotting script has some issues. The later versions of the r-packages do not install their own dependencies. I checked the versions I tested previously and they work fine. I will make a pull request for the fixed package versions and submit it (pending Natasha's input). Thanks again for you help with this!

**Comment by tseemann** [comment]
That is frustrating re: badly written R conda pkgs....
