### ISSUE TITLE
use parallel instead of xargs ?

### ISSUE THREAD

**Issue by tseemann** [SionBayliss/PIRATE#27]
```
./scripts/run_PIRATE.pl:        `cat $pirate_dir/genome_list.txt | xargs -I {} cat $pirate_dir/genome_multifastas/{}.fasta > $pirate_dir/pan_sequences.fasta`;
```

I think this command just cats all the files in the list together into a single fasta?

Having issues in conda with `-I {}` .
Can we use `parallel -j1` somehow instead?

UPDATE: not sure if this is the real problem

**Comment by SionBayliss** [comment]
It does! I will update it in the next push. Doesn't seem to get in the was of conda atm.

**Comment by SionBayliss** [comment]
Just saw your PR. Much appreciated!
