### ISSUE TITLE
Problem with creating core alignments

### ISSUE THREAD

**Issue by Tao2020yes** [SionBayliss/PIRATE#32]
At the end of the analysis using "PIRATE -i ./test_gff3 -f "tRNA,rRNA,CDS" -s "95,96,97,98" -k "--cd-low 98 -e 1E-12" -a", it says below
Can't use an undefined value as an ARRAY reference at /home/XXXXX/.conda/envs/conda2env/scripts/create_pangenome_alignment.pl line 384, <GC> line 9549.
 - 0 clusters to be printed to output
 - 100 % clusters added to output

 - ERROR: creating core concatenate failed
 - completed in: 0s
Could you help address this issue? Thanks

**Comment by SionBayliss** [comment]
It is likely that you don't have any clusters that the alignment script considers core i.e. >95% of isolates and dosage/copy number <1.25. You can check that this is the case in the tabular output in the log or summary file. If this is the case and you want to modify the default thresholds to use a more relaxed core definition then you can run the script(s) manually. 

```
create_pangenome_alignment.pl -i /path/to/PIRATE.gene_families.tab -f /path/to/feature_sequences/ -o /path/to/output_fasta.fasta -g /path/to/output_gff.gff -t percentage_threshold (integer) -d dosage_threshold(floating_point)
```

If dosage/copy number is an issue you may have a problematic dataset. If this is the case let me know and I can suggest some advanced settings that should improve cluster resolution.

**Comment by cizydorczyk** [comment]
Is there somewhere where the options for core threshold and dosage threshold are documented?

I'm running PIRATE v.1.0.3 and the "-t" option seems to set threads, not core threshold, and I can't find the "-d" option in any of the help menus.

Thanks!
Conrad

**Comment by SionBayliss** [comment]
Hi Conrad, 

You will need to run the script create_pangenome_alignment.pl (in /PIRATE/scripts/ directory) separately as detailed above. There is currently no options for changing these defaults from the main PIRATE script. I will consider adding them in a future update.

All the best,
Sion
