### ISSUE TITLE
problem with fasttree and --pan-off 

### ISSUE THREAD

**Issue by aysunrhn** [SionBayliss/PIRATE#33]
Hi,

I've been trying out PIRATE on some bacterial genomes, and I had a couple questions
1. I have FastTree binary in my path, and when I run `check_dependencies.pl` under scripts it all seems fine. I checked closed issues on this, and I think you did some changes to fix this before but `in run_PIRATE.pl`

https://github.com/SionBayliss/PIRATE/blob/8e857f158755666ea1efdd85bc144d3a19ce9e92/scripts/run_PIRATE.pl#L453

In my installation, `command -v fasttree;` returns false but `command -v FastTree;` is true so PIRATE couldn't generate a tree

2. Also, I couldn't figure out in what context '--pan-off' can be useful exactly? Do you have any examples for when I might want to try this?

Thanks!

PS. really like the random pirate jokes at the end! Glad to see I'm not the only one who prefers some humor to exit flag 0

**Comment by SionBayliss** [comment]
Hi Aysun, 

Good catch! I have just pushed a fix to master. Let me know if there are any other issues.

--pan-off is useful if you need to run any of the post-processing steps separately, such as paralog splitting with modified settings. It has also been useful for testing the code on larger datasets where rerunning BLAST/DIAMOND is unfeasible.

If you have any good PIRATE jokes just let me know and I will add them in!

All the best,
Sion

**Comment by aysunrhn** [comment]
Ah I see, just checked the usage section under Wiki again and from what I understand, the `--pan-off` option makes sense if I first run PIRATE with paralog classification off. Thanks, closing the issue!
