### ISSUE TITLE
PIRATE_to_roary.pl: command not found

### ISSUE THREAD

**Issue by mabouelk** [SionBayliss/PIRATE#36]
I am trying to convert the output files but not working. Any help?

**Comment by SionBayliss** [comment]
The script can be found in the /tools/convert_format/ directory of your PIRATE installation folder e.g. path_to_PIRATE/tools/convert_format/PIRATE_to_roary.pl

**Comment by mabouelk** [comment]
Thank you

**Comment by iferres** [comment]
Hi, I have a related problem. I can't find the PIRATE_to_roary.pl script when installed through conda. Would be nice to have it that way too.
Thanks for the software btw!

**Comment by SionBayliss** [comment]
Hi Ignacio,

They are downloaded but not in PATH. They can be found in ~/path_to_miniconda/envs/name_of_pirate_environment/tools/ I believe. I agree that they should probably be in PATH 🙂

All the best,
Sion


________________________________

**Comment by iferres** [comment]
I found it! My bad. Yes, it will avoid people like me asking for the scripts in the github issue tracker :sweat_smile:
Thanks!
