### ISSUE TITLE
  - creating co-ordinate files   Failed

### ISSUE THREAD

**Issue by limin321** [SionBayliss/PIRATE#44]
Hi, 

I set up running PIRATE on a collection of bacterial genomes, using the following command,
```bash
PIRATE -i ./gff/ -o ./panOut -a -r -f "rRNA, tRNA" -k "-f 6" -t 40 
```

However, it failed in few second with error message, 
"- ERROR: feature co-ordinate extraction failed"

Can anyone please help me explain what may go wrong, how should i fix this problem?

Thanks a lot.

**Comment by SionBayliss** [comment]
Hi Limin, 

How were the GFF3 files created? Have the rRNA and tRNA features been annotated correctly in them?

Could you run it on a small subset of files to see if it works on only a handful?

All the best,
Sion

**Comment by limin321** [comment]
> Hi Limin,
> 
> How were the GFF3 files created? Have the rRNA and tRNA features been annotated correctly in them?
> 
> Could you run it on a small subset of files to see if it works on only a handful?
> 
> All the best,
> Sion

Hi Sion

I used prokka to create gff files. Here is the prokka command I used for generating gff files.
```
prokka --kingdom Bacteria --centre X --compliant --outdir ${base} --locustag ${base} ${dir}/${base}.fna --cpus 0 --force --prefix ${base} --addgenes
```
However, after I deleted ```-f "rRNA, tRNA" ```
```
PIRATE -i ./gff/ -o ./panOut -a -r -k "-f 6" -t 40 
```
PIRATE works now without -f flag. Not sure why this happens.

Thanks.

**Comment by SionBayliss** [comment]
The -f flag directs PIRATE to run on a list of features. By default the features are CDS and will be translated into amino acid sequence. If you are happy running PIRATE on CDS/gene features then the run you have started should be suitable. 

By using the -f flag you directed pirate to only work on tRNA and rRNA features which would be processed as nucleotide sequence. I believe that prokka should have annotated tRNA and rRNA based upon the flags you set so I do not understand why PIRATE did not work on your files previously. I would be happy to look over a subsection of you GFF3 to work out why they didn't run with the -f flag if you would be happy to email them to me (or attach them here). 

S

**Comment by limin321** [comment]
> The -f flag directs PIRATE to run on a list of features. By default the features are CDS and will be translated into amino acid sequence. If you are happy running PIRATE on CDS/gene features then the run you have started should be suitable.
> 
> By using the -f flag you directed pirate to only work on tRNA and rRNA features which would be processed as nucleotide sequence. I believe that prokka should have annotated tRNA and rRNA based upon the flags you set so I do not understand why PIRATE did not work on your files previously. I would be happy to look over a subsection of you GFF3 to work out why they didn't run with the -f flag if you would be happy to email them to me (or attach them here).
> 
> S

Hi S

Thank you so much for the explaination,
I included two gff files and send them to author@noreply.github.com this email. Not sure if you can get them.
Really appreciate that you would like to test my data.

If you haven't got the gff files, please let me know, I will send again if you give me the email address.

Best,
LC

**Comment by SionBayliss** [comment]
Do you need to extract rRNA and tRNA? I didn't receive them. You can find my personal email on the PIRATE paper or just attach compressed versions here.

S

**Comment by limin321** [comment]
> Do you need to extract rRNA and tRNA? I didn't receive them. You can find my personal email on the PIRATE paper or just attach compressed versions here.
> 
> S

Hi S,

Thank you so much. Yes, I am panning to look at the difference of rRNA and tRNA of different genomes. And I just sent the gff files again through the email in PIRATE paper.

Best,
LC

**Comment by SionBayliss** [comment]
Hi Limin, 

I just ran PIRATE on your example files and it worked without error using:

```
PIRATE -i ./ -o PIRATE -f "tRNA,rRNA" -a -k '-f 6'
```

I installed PIRATE using conda. You may need to check it is installed correctly on your system. 

S

**Comment by limin321** [comment]
> Hi Limin,
> 
> I just ran PIRATE on your example files and it worked without error using:
> 
> ```
> PIRATE -i ./ -o PIRATE -f "tRNA,rRNA" -a -k '-f 6'
> ```
> 
> I installed PIRATE using conda. You may need to check it is installed correctly on your system.
> 
> S

Hi S,

Thank you so much for testing my data. I also use conda to install PIRATE. 
By comparing you codes, I figured out why I failed. 

your command:
```
PIRATE -i ./ -o PIRATE -f "tRNA,rRNA" -a -k '-f 6'
```
my command 
```
PIRATE -i ./ -o PIRATE -f "tRNA, rRNA" -a -k '-f 6'
```
I added extra space before rRNA, leading to the error message. I didn't know the extra space will cause error.  
Really appreciate that. 

Best,
Limin

**Comment by SionBayliss** [comment]
Well tracked down. I will make a note to catch that in future versions!

I hope you find the software useful. Please let me know if you have any further issues.

All the best,
Sion
