### ISSUE TITLE
PIRATE to Roary

### ISSUE THREAD

**Issue by JParraV** [SionBayliss/PIRATE#46]
Hi,

I am trying to covert the PIRATE output to Roary. However, I got "input directory not found", even though it is there.
```
hsb18158@sipbsmicro ~/PIRATE % bin/PIRATE PIRATE_to_roary.pl -i /home/hsb18158/data/PIRATE_output/PIRATE.gene_families.tsv -o /home/hsb18158/data/PIRATE_to_roary/gene_families.csv
ERROR: input directory not
hsb18158@sipbsmicro ~/PIRATE % bin/PIRATE convert_to_roary.pl -i /home/hsb18158/data/PIRATE_output/PIRATE.gene_families.tsv -o /home/hsb18158/data/PIRATE_to_roary/gene_families.csv
ERROR: input directory not found.
```
Any suggestion?

Thank you,
Parra

**Comment by SionBayliss** [comment]
Hi Parra, 

It looks like you might be using an older version of the script. Try the most recent one from github. 

All the best,
Sion

**Comment by JParraV** [comment]
Hi,

I tried both. But I sorted it out. It was entirely my fault. I installed PIRATE by cloning the repository and I tried to run the script `PIRATE_to_roary.pl` from the bin folder. Sorry. It's amended and the results look great.

Thanks!
Parra
