### ISSUE TITLE
Plasmid comparison

### ISSUE THREAD

**Issue by jellila** [SionBayliss/PIRATE#49]
Hello 🙂

I would like to ask you some help/suggestions please. 
I am trying to create an image (either with brig or cgview or circos) where three plasmids are compared. Every plasmid comes from a different strain and they have some differences. My idea was to create a sort of pan genome of the three plasmids as a reference, and then blast every plasmid around this pan genome, showing the genes are present in every single plasmid. I hope this makes sense! I use pirate to perform the analyses, but actually i don't really know how to go on. I don't think that the pan_sequences.fasta file is what I need (since it contains the same gene multiple times), but also the representative_sequences.ffn is not ideal (as it only has one representative per gene cluster, and if a plasmids have duplications I won't be able to show them). 
Would anyone please have any suggestions? 

Thank oyu.

Laura

**Comment by SionBayliss** [comment]
Hi Laura, 

PIRATE has already done the BLASTing for you, The presence/absence file (PIRATE.gene_families.tsv) should contain the relevant info. 

All the best,
Sion

**Comment by jellila** [comment]
Thanks Sion!

**Comment by SionBayliss** [comment]
Thanks! 

Feel free to suggest some for the next release :)
