### ISSUE TITLE
need suggestions on my PIRATE commend.

### ISSUE THREAD

**Issue by limin321** [SionBayliss/PIRATE#50]
Hello
I run PIRATE on my around 300 bacterium genomes, using the following command:
```
PIRATE -i ./311gff/ -o ./311Agro_panOut -a -r -k "-f 6" -t 40   
```
  Which is, I used default identity thresholds. 
The ~300 strains ANI values ranges from 77.556 to 100 %.
There is one gene called tolB which are highly identical > 98%, however, in the PIRATE_gene_presence_absence.ordered.tsv table, these three genes were classified into three gene_families. 
e.g. tolB gene_family g000845, the cutoff PIRATE used is 50%; 
tolB in g032043_000006 gene family, the cutoff is 98%; 
tolB in g044923_000006 gene family, the cutoff is 98%. 

However, the interesting is: g032043_000006 is only found in one species(containing 29 strains), and g044923_000006 gene family is also only found in one specific species (only three strains), though g000845, g032043, g044923 are highly similar > 98.8%. 
Feels like the default setting somehow is able to put genes from the same species in one gene family, at least for gene tolB in these two species. I also checked tolB in other species, then I got the 50% cutoff gene family g000845. 
and then how to interpret why the three gene family are not cluster as one gene family, and one even was  clustered with other genes with 50% cutoff. I am really confused on how to interpret this data.
I am wondering if you can give some suggestions on how to modify my PIRATE  codes. 
I would like to try different things to compare based on your experience.
Actually I sent you email though never get your reply. Now I am posting here to ask for help again.
I am sorry if my question is too basic to ask.
Really appreciate your help.

Best,
Limin

**Comment by SionBayliss** [comment]
Hi Limin, 

It has to do with how PIRATE splits gene families containing paralogous genes. The largest gene family is likely to be present at high frequency (g000845). You will most likely find that the gene families g032043_000006 and g044923_000006 are present in genomes which contain a copy of g000845. PIRATE has identified them as multi-copies of g000845 and split them from the main gene family accordingly.  You can disable this behaviour with the '--para-off' flag but no paralogs will be identified. 

Sorry I didn't get your email but support on here is preferred as it can be used to help future users. 

All the best,
Sion

**Comment by SionBayliss** [comment]
Hi Limin, 

Could you attach your three genomes of interest and the PIRATE.gene_families.tsv file please. 

The gene_families denotes an identifier for the cluster which including alleles at all AA/MCL thresholds. The allele column denotes a specific cluster of loci at a single AA threshold. In the PIRATE.gene_families.tsv file this is functionally identical information but the distinction is important for interpretation of the PIRATE.unique_alleles.tsv file.  

All the best,
Sion

**Comment by limin321** [comment]
> Hi Limin,
> 
> Could you attach your three genomes of interest and the PIRATE.gene_families.tsv file please.
> 
> The gene_families denotes an identifier for the cluster which including alleles at all AA/MCL thresholds. The allele column denotes a specific cluster of loci at a single AA threshold. In the PIRATE.gene_families.tsv file this is functionally identical information but the distinction is important for interpretation of the PIRATE.unique_alleles.tsv file.
> 
> All the best,
> Sion
Hi Sion

Thank you for trying to help. considering my data is unpublished yet, can I email you? 
s.bayliss@bath.ac.uk   is this email address working. this is the one I sent last time that you seems not able to get it. I just want to confirm it.

Best,
Limin

**Comment by limin321** [comment]
> > Hi Limin,
> > Could you attach your three genomes of interest and the PIRATE.gene_families.tsv file please.
> > The gene_families denotes an identifier for the cluster which including alleles at all AA/MCL thresholds. The allele column denotes a specific cluster of loci at a single AA threshold. In the PIRATE.gene_families.tsv file this is functionally identical information but the distinction is important for interpretation of the PIRATE.unique_alleles.tsv file.
> > All the best,
> > Sion
> > Hi Sion
> 
Hi Sion

I just emailed you my data, please let me know if you do not get the email.

Best,
Limin

**Comment by SionBayliss** [comment]
Hi Limin, 

I haven't received it. Could you send them to s_bayliss(at)hotmail.co.uk. It will probably be next week before I can look at this. 

All the best,
Sion

**Comment by limin321** [comment]
> s_bayliss(at)hotmail.co.uk

Hi Sion

I just sent again to the new email. Please let me know if you don't get it.

Best,
Limin

**Comment by SionBayliss** [comment]
Hi Limin, 

I think I have found the source of your confusion. PIRATE renames loci to ensure consistent parsable nomenclature (see README). When working with raw PIRATE outputs you should refer to the ./modified_gff/*gff for the position and names of features. If you want to convert the PIRATE outputs to have the original locus_tags/IDs you can use the command:

```
 ~/Desktop/github/PIRATE/tools/subsetting/subsample_outputs.pl -i ./PIRATE.gene_families.tsv -g ./modified_gffs/ -o PIRATE.gene_families.renamed.tsv --field "prev_ID"
``` 

This workflow is not ideal but it means that PIRATE is compatible with as many datasets as possible (I have seen some extremely non-standard locus_tags). I ran your dataset and 
 after converting to original locus tags CC001_03341 - Kin002_04269 - Sta004_03864 clustered together.  

All the best,
Sion

**Comment by limin321** [comment]
> Hi Limin,
> 
> I think I have found the source of your confusion. PIRATE renames loci to ensure consistent parsable nomenclature (see README). When working with raw PIRATE outputs you should refer to the ./modified_gff/*gff for the position and names of features. If you want to convert the PIRATE outputs to have the original locus_tags/IDs you can use the command:
> 
> ```
>  ~/Desktop/github/PIRATE/tools/subsetting/subsample_outputs.pl -i ./PIRATE.gene_families.tsv -g ./modified_gffs/ -o PIRATE.gene_families.renamed.tsv --field "prev_ID"
> ```
> 
> This workflow is not ideal but it means that PIRATE is compatible with as many datasets as possible (I have seen some extremely non-standard locus_tags). I ran your dataset and
> after converting to original locus tags CC001_03341 - Kin002_04269 - Sta004_03864 clustered together.
> 
> All the best,
> Sion

Thank you so much, I just got time working on this again, could you please do not close this issue for now, until I finished my analysis.  Thanks a lot.
Best,
Limin

**Comment by limin321** [comment]
> Hi Limin,
> 
> I think I have found the source of your confusion. PIRATE renames loci to ensure consistent parsable nomenclature (see README). When working with raw PIRATE outputs you should refer to the ./modified_gff/*gff for the position and names of features. If you want to convert the PIRATE outputs to have the original locus_tags/IDs you can use the command:
> 
> ```
>  ~/Desktop/github/PIRATE/tools/subsetting/subsample_outputs.pl -i ./PIRATE.gene_families.tsv -g ./modified_gffs/ -o PIRATE.gene_families.renamed.tsv --field "prev_ID"
> ```
> 
> This workflow is not ideal but it means that PIRATE is compatible with as many datasets as possible (I have seen some extremely non-standard locus_tags). I ran your dataset and
> after converting to original locus tags CC001_03341 - Kin002_04269 - Sta004_03864 clustered together.
> 
> All the best,
> Sion

Hi Sion,

Thank you so much. After converting the original table, everything works well so far.
I have one more question, one of the pirate output file called pangenome.gfa, representing all unique connections between gene families. Could you please explain a little bit more, what are those unique connections?
Because I used the gene_presence_absence.csv table to run coinfinder, which run association analysis between gene families. Then I was thinking what is the difference of the unique connections from PIRATE pangenome.gfa and associate groups from coinfinder?

Thanks a lot.
Best,
Limin

**Comment by SionBayliss** [comment]
Hi Limin, 

The gfa file specification can be found here - https://github.com/GFA-spec/GFA-spec. You can load the file into Bandage (https://rrwick.github.io/Bandage/) to visualise a graph of your pangenome. I have found it useful. I will close this issue as it has been resolved. 

Cheers,,
Sion
