### ISSUE TITLE
Min length of gene families

### ISSUE THREAD

**Issue by plasmid02** [SionBayliss/PIRATE#51]
Noticed that the min_length for the members of gene families is 123 bp, although some genes in the input were as small as 75 bp.  Is there a  parameter that can be altered that allows these small genes to be included in families?

**Comment by SionBayliss** [comment]
Hi Tim, 

There isn't a parameter that can be accessed from the main command currently. If you want a quick hack the you can modify the line below in run_PIRATE.pl to include "-t 75" 

```
	# extract sequences.
	`cat $pirate_dir/genome_list.txt | parallel -k -j $threads \"perl $script_path/extract_feature_sequences.pl -s {} -d $pirate_dir -o $pirate_dir/genome_multifastas/{}.fasta $e_args >> $pirate_dir/gff_parser_log.txt 2>> $pirate_dir/gff_parser_log.txt\"`;
``` 

e.g. 
```
	# extract sequences.
	`cat $pirate_dir/genome_list.txt | parallel -k -j $threads \"perl $script_path/extract_feature_sequences.pl -t 75 -s {} -d $pirate_dir -o $pirate_dir/genome_multifastas/{}.fasta $e_args >> $pirate_dir/gff_parser_log.txt 2>> $pirate_dir/gff_parser_log.txt\"`;
```

I am happy to add a branch with this option to the main script and include it in the next release. 

All the best,
Sion

**Comment by plasmid02** [comment]
Hi Sion - thanks for the super quick reply.  Will use this hack and also would be interested in having a branch available in the next release.  Tim

**Comment by SionBayliss** [comment]
When I get a spare minute I will set one up for you :)

**Comment by SionBayliss** [comment]
I don't see the nohup warnings you were getting when I created a branch with the same option. Are you still seeing them and are the outputs okay?

S

**Comment by SionBayliss** [comment]
I found an error message with link_clysters.pl but it looks like it maybe an issue of rerunning PIRATE in the same directory with different settings. When I sent outputs to a fresh directory it didn't occur. I will push to master shortly. Thank you for your help and testing. 

S

**Comment by rpetit3** [comment]
Hi @SionBayliss!

I noticed the PR for this feature was merged then reverted (https://github.com/SionBayliss/PIRATE/pull/55). Are there still plans to implement this in the future?

Thanks!

**Comment by SionBayliss** [comment]
I have merged this with another commit that I wanted to push together. The revert was due to reading about the nohup errors after merging and then slightly panicking. 

I have pushed them both to master now. The master branch has all of the changes that I previously reverted.

**Comment by rpetit3** [comment]
I should have waited! Thanks Sion!
