### ISSUE TITLE
Use with eukaryotic/intron containing models

### ISSUE THREAD

**Issue by hyphaltip** [SionBayliss/PIRATE#52]
I realize currently there is a one CDS per locus model and this is very much a bacteria-focus project. But are there reasons it cannot work with other systems? 
I have done my own work around using mRNA feature and nucleotide comparisons which does achieve results, but I wonder if you are open to code which deal with multi-CDS features for a single mRNA feature that could be spliced together to make the feature sequence that is compared?

**Comment by SionBayliss** [comment]
Hi Jason, 

I would be open to collaboration to support PIRATE being modified with that functionality but I currently do not have the required to to do the required work myself. It would require some relatively heavy QC and rewriting of some of the scripts around gene annotation and sequence extraction.  

All the best,
Sion

**Comment by hyphaltip** [comment]
Sure thing - I was proposing to work on it from my end - I can start a branch in my fork and see how far we can get.

**Comment by SionBayliss** [comment]
Great, let me know if I can help. Most of the code is annotated but some may be impenetrable.
