### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by pavlo888** [SionBayliss/PIRATE#6]
Hi, 

I am trying to install the package but apparently Conda cannot find it. Would you please have look at this issue and let me know how to install the pirate package? I am eager to try it out. 

Cheers, 
Pablo

**Comment by SionBayliss** [comment]
Hi Pablo, 

PIRATE relies on the default bioconda channels for installation. I have updated the readme to reflect this. 

It should install if you run:
```
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
``` 
followed by:
```
conda install -c sionbayliss pirate 
```

Could you let me know if that resolves your problems?

All the best,
Sion

**Comment by pavlo888** [comment]
Hi Sion,

Thank you for your fast response. I have run the the commands to activate
the specific Conda channels that you suggested. However, it turns out that
I already had those channels activated.

Then I ran the install command for pirate and unfortunately it did not
work.

This is what I get in the prompt:

(pirate) Pablos-MacBook-Air:pirate_output pablovargas$ conda install -c
sionbayliss pirate

Collecting package metadata: done

Solving environment: failed


PackagesNotFoundError: The following packages are not available from
current channels:


  - pirate


Current channels:


  - https://conda.anaconda.org/sionbayliss/osx-64

  - https://conda.anaconda.org/sionbayliss/noarch

  - https://conda.anaconda.org/conda-forge/osx-64

  - https://conda.anaconda.org/conda-forge/noarch

  - https://conda.anaconda.org/bioconda/osx-64

  - https://conda.anaconda.org/bioconda/noarch

  - https://repo.anaconda.com/pkgs/main/osx-64

  - https://repo.anaconda.com/pkgs/main/noarch

  - https://repo.anaconda.com/pkgs/free/osx-64

  - https://repo.anaconda.com/pkgs/free/noarch

  - https://repo.anaconda.com/pkgs/r/osx-64

  - https://repo.anaconda.com/pkgs/r/noarch

  - https://conda.anaconda.org/r/osx-64

  - https://conda.anaconda.org/r/noarch


To search for alternate channels that may provide the conda package you're

looking for, navigate to


    https://anaconda.org


and use the search bar at the top of the page.



(pirate) Pablos-MacBook-Air:pirate_output pablovargas$

Hopefully, you could help me find a solution because I am very interested
in trying this package.

Best regards,
Pablo

**Comment by SionBayliss** [comment]
Hi Pablo, 

The conda installation (and development of PIRATE in general) was built on a linux operating system. The conda build of PIRATE is currently incompatible with MacOS. Assuming the dependencies are available for MacOS via conda you can install them with:

conda install perl-bioperl==1.7.2 mcl>=14.137 mafft==7.310 cd-hit>=4.6.4 fasttree>=2.1.10 diamond>=0.9.14 blast>=2.2.31 parallel>=20170422

And then git clone the github repo. If the dependencies are in your PATH then the PIRATE executable (/*github_repo*/bin/PIRATE) should function. I do not have a MacOS machine so I haven't tested this, there maybe compatibility issues between the operating systems.

Please let me know if this works as it may be of use to other users.

**Comment by pavlo888** [comment]
Hi Sion,

I installed all the dependencies in a conda environment and then used the
PIRATE executable while the environment was active. It worked!

Thank you for your support.

Best regards,
Pablo

**Comment by SionBayliss** [comment]
Hi Pablo, 

Thanks for the feedback. I am glad it worked. I will update the readme for Mac users. 

Cheers,
Sion
