### ISSUE TITLE
gaps in core_alignment.fasta

### ISSUE THREAD

**Issue by haruosuz** [SionBayliss/PIRATE#65]
[5931919.zip](https://github.com/SionBayliss/PIRATE/files/5936400/5931919.zip)

Attached is a result of comparing four plasmid sequences (CP062120 U67194 AB231906 AM261282) using PIRATE.

There were so many gaps for CP062120 in core_alignment.fasta (94.09% of the 27471 alphabets "-ACGNT" are gaps "-"). I wonder if this is a bug or something?

Regarding whole nucleotide sequence, length is longer in CP062120 (197271 bp) than in the other sequences (AM261282, U67194, and AB231906, ranging from 46557 to 54383 bp), while GC content is not so different between the four sequences (ranging from 60.84 to 65.33).

**Comment by SionBayliss** [comment]
It looks like your plasmid sequences are quite divergent, of your core genes (~25% of total genes) almost all of them are ~30-50% sequence divergence. Additionally, many of those genes also show min/max length variation. 

Ns/- are added to represent sequence/genes missing in individual isolates e.g. if genomeA does not have a copy of gene1 then the length of the alignment for gene1 will be represented by Ns. Similarly Ns will be added by MAFFT where there are alignment gaps between divergent or different length sequences. 

I would suggest you curate the genes you think are useful to align, e.g. have a similar copy number and length, before aligning these genes individually. Your dataset is sufficiently small that this sort of manual inspection/analysis would be warranted and efficient. 

I hope that helps.

All the best,
Sion

**Comment by haruosuz** [comment]
Dear Sion: Thank you for your comments.

- If I understand correctly, there will be no N if % of isolates a gene must be in to be core is set at 100. https://github.com/SionBayliss/PIRATE/issues/60

- To curate the genes, could you provide example codes to extract individual gene alignments?

- Are there PIRATE options or support scripts to generate **core_alignment.fasta** from subsets of gene alignments?

- PIRATE can use alignment tools such as MACSE (https://academic.oup.com/mbe/article/35/10/2582/5079334) as well as MAFFT?

**Comment by haruosuz** [comment]
I would be most grateful if you could provide example codes to extract amino acid and nucleotide sequences for core genes only from **feature_sequences directory**.

**Comment by haruosuz** [comment]
Dear @SionBayliss : Of the >200 plasmid sequences, 4 was selected for this report.

I would be most grateful if you could clarify what `core_alignment` contains (criteria used to define core genes)?

I checked the output files:
- `PIRATE.gene_families.ordered.tsv`: The 35 of the 139 gene families in 4 genomes are `number_genomes == 4`.
- `PIRATE.pangenome_summary.txt`: #clusters is 35 for %isolates = 95-100%.
- `core_alignment.gff`: There are 29 Pangenome CDS.

The multiple alignments for the 29 gene families (`number_genomes == 4 & number_duplicated_loci < 2`) were concatenated to create `core_alignment.fasta`?
The 6 gene families (`number_genomes == 4 & number_duplicated_loci > 1`) were excluded from the core genes?
