### ISSUE TITLE
extract_feature_sequences.pl failed

### ISSUE THREAD

**Issue by 3josh4** [SionBayliss/PIRATE#68]
Hi there, I'm trying to run PIRATE on Ubuntu, but I get the following error message: 

<img width="586" alt="pirate error" src="https://user-images.githubusercontent.com/42725611/111034478-db00a700-83e3-11eb-8540-ae25c74c886e.png">

There seems to be an issue with dependencies. I installed via apt-get and my system says BioPerl is up to date... any ideas on how to troubleshoot this?  

Thank you in advance! 
 --Josh

**Comment by SionBayliss** [comment]
Hi Josh, 

Firstly, I would suggest installing via conda/miniconda as this should remove any dependency issues. Is there any more info in the log file? 

All the best,
Sion

**Comment by 3josh4** [comment]
Hi Sion, thanks very much for your response. I was able to get PIRATE working fine after all, I think I simply exceeded the number of threads allowed by my CPU, so my mistake there! 

Appreciate your help! 
--Josh
