### ISSUE TITLE
error observed during "aligning all feature sequences"

### ISSUE THREAD

**Issue by fengyuchengdu** [SionBayliss/PIRATE#69]
An error was observed during step "Aligning all feature sequences", although the program looked like finished successfully. 

I'm wondering if this error is accepted (the results are reliable), and how can I solve this?

Many thanks.  

-------------------------------

Aligning all feature sequences:
 - number of groups : 44247
 - extracting sequences from gffs
 - aligning group sequences using MAFFT
 - 69 % alignedCan't call method "each_seq" on an undefined value at /home/zong/anaconda3/envs/pangenome/scripts/aa_align_to_nucleotide.pl line 111.
 - ERROR: aa_align_to_nucleotide.pl threw an error after 35392 samples
 - 100 % aligned
 - completed in: 769s

Creating full pangenome alignment:
 - 44247 clusters to be printed to output
 - WARNING: no fasta file for g037324 found in /home/zong/Desktop/tree/gff/result_pirate/feature_sequences/
 - 100 % clusters added to output
 - printing to output file
 - writing gff annotation file
 - Output alignment length: 36118938 bp
 - completed in: 52s

Creating core alignment:
 - 2135 clusters to be printed to output
 - 100 % clusters added to output
 - printing to output file
 - writing gff annotation file
 - Output alignment length: 2326806 bp
 - completed in: 14s

-------------------------------

PIRATE completed in 62066s

Q: Why does it take pirates so long to learn the alphabet?
A: Because they can spend years at C.

YARR!

-------------------------------

**Comment by SionBayliss** [comment]
Dear Feng Yu, 

That is odd. Unfortunately, I didn't make the error message terrible informative. That specific error message does not kill the script so it is likely that it has only failed to align a single gene g037324 as indicated by the error below.  If you could inspect that file and identify if there are any obvious issue with it (e.g. unalignable characters, odd formatting, blank sequences) it would be much appreciated. 

You can do this by re-aligning that problematic gene. If you provide a modified PIRATE.gene_families.tsv fie to align_feature_sequences.pl which only contains a single line for g037324 then it will realign that problem gene:

```
perl ./PIRATE_script_path/align_feature_sequences.pl --dosage 1.25 -i PIRATE.gene_familes.MODIFIED.tsv -g ./PIRATE/modified_gffs/ -o PIRATE/feature_sequences/ -p 1
```

If you comment out (put a #) before the line below in align_feature_sequences.pl then you should be able to view the intermediate file created by this script which will contain the sequences to be aligned:

```
	unlink "$output_dir/$cluster.fasta";
``` 
This should give you some insight into why the script is failing on that gene. 

I hope that helps,
Sion

**Comment by josedanfoliveros** [comment]
Good day.

I came across a similar issue to Feng Yu when I tested my dataset against these samples.

---
Aligning all feature sequences:
 - number of groups : 13471
 - extracting sequences from gffs
 - aligning group sequences using MAFFT
 - 0 % aligned - ERROR: aa_align_to_nucleotide.pl threw an error after 1347 samples
 - ERROR: aa_align_to_nucleotide.pl threw an error after 2694 samples
 - 19 % aligned - ERROR: aa_align_to_nucleotide.pl threw an error after 4041 samples
 - 29 % aligned - ERROR: aa_align_to_nucleotide.pl threw an error after 5388 samples
 - 39 % aligned - ERROR: aa_align_to_nucleotide.pl threw an error after 6735 samples
 - 49 % aligned - ERROR: aa_align_to_nucleotide.pl threw an error after 8082 samples
 - 59 % aligned - ERROR: aa_align_to_nucleotide.pl threw an error after 9429 samples
 - 69 % aligned - ERROR: aa_align_to_nucleotide.pl threw an error after 10776 samples
 - 79 % aligned - ERROR: aa_align_to_nucleotide.pl threw an error after 12123 samples
 - 89 % aligned - ERROR: aa_align_to_nucleotide.pl threw an error after 13470 samples
 - 99 % aligned - 100 % aligned - 100 % aligned

Creating full pangenome alignment:
 - 13471 clusters to be printed to output
 - WARNING: no fasta file for g000677 found in /~/.../feature_sequences/ (this goes on for all 23 sequences where the error took place)
 ---

For now, I followed through with creating the intermediate files. However, I was unsure from there with how to proceed, but I decided to try to realign each group’s sequences and convert this to protein realignments.

Thank you very much for your time.

Regards,
Daniel
