### ISSUE TITLE
How do you tell which gene families are single-copy or multi-copy?

### ISSUE THREAD

**Issue by junhiuqiu** [SionBayliss/PIRATE#75]
Hi. After I successfully ran PIRATE, I wanted to build an evolutionary tree from a single copy of the core genome  ,I would like to know how to determine if gene family is a single copy from the output file  ,Thank you very much!!!

**Comment by SionBayliss** [comment]
The average_dosage information should tell you how many copies there are of each gene (1 = one copy per genome, >1 multiple copies in some genomes).

**Comment by junhiuqiu** [comment]
Thank you very much!!!!!!
