### ISSUE TITLE
Average_dose =1 is appropriate to determine whether a gene family is a single copy？

### ISSUE THREAD

**Issue by junhiuqiu** [SionBayliss/PIRATE#77]
I'm sorry to bother you again，I've chosen the Average_dosage =1 gene family as you suggested, but they're not all single copie，I found the protein sequence files of corresponding gene families in Feature_sequences, and the number of protein sequences in the files was larger than the number of genomes I provided，Does that mean these gene families aren't really single copies？This happens even if I choose average_dose=1 and min_dose=1 and max_dose=1

**Comment by SionBayliss** [comment]
Could you send me your input and output files so that I can check this behaviour?
