### ISSUE TITLE
Undefined subroutine &main::translate called

### ISSUE THREAD

**Issue by salrodpal** [SionBayliss/PIRATE#79]
Hi,
I have installed PIRATE using CONDA:
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
conda install pirate 

I am trying to check it: 
PIRATE --check 

However it always threw out an error saying: 
 - ERROR: extract_feature_sequences.pl failed
 - ERROR: PIRATE did not run correctly:
 - ERROR: PIRATE was not able to extract sequences from GFFS
 - ERROR: PIRATE was not able to construct pangenome
 - ERROR: PIRATE was not able to classify paralogs
 - ERROR: PIRATE could not make summary files

And when I view gff_parser_log file:
 - WARNING: /home/saludrp/anaconda3/envs/pirate_env/test/HO_5096_0412_test.gff - contig HO_5096_0412 contains non-ATCGN characters - replacing with Ns
Undefined subroutine &main::translate called at /home/saludrp/anaconda3/envs/pirate_env/scripts/extract_feature_sequences.pl line 214, <COORDS> line 2.
Undefined subroutine &main::translate called at /home/saludrp/anaconda3/envs/pirate_env/scripts/extract_feature_sequences.pl line 214, <COORDS> line 2.
Undefined subroutine &main::translate called at /home/saludrp/anaconda3/envs/pirate_env/scripts/extract_feature_sequences.pl line 214, <COORDS> line 2.
Undefined subroutine &main::translate called at /home/saludrp/anaconda3/envs/pirate_env/scripts/extract_feature_sequences.pl line 214, <COORDS> line 2.

I don´t know where the problem is, and how I can solve it.
Thanks a lot!

**Comment by SionBayliss** [comment]
This seems to be an issue with a recently updated dependency, namely bioperl. 

I will get that corrected on the conda recipe, but in the mean time you can downgrade bioperl using:

```
conda install perl-bioperl==1.7.2
```

I have tested this and it should fix your issue. 

I will leave this open until I have fixed the conda recipe. I am unavailable for ~1 week but should have it fixed on my return in mid-March. 

All the best,
Sion

**Comment by salrodpal** [comment]
I have fixed with your recommendation. 
Thank you!!
