### ISSUE TITLE
fasttree vs FastTree ?

### ISSUE THREAD

**Issue by tseemann** [SionBayliss/PIRATE#8]
```
./PIRATE  --check
 - WARNING: fasttree not found in system path, a binary presence-absence tree will not be created.
```

The standard exe name is `FastTree` - any chance you can support both?

I did `cd PIRATE/bin && ln -s $(which FastTree) fasttree` for now

**Comment by SionBayliss** [comment]
Both invocations should be supported on newest branch (split_correction) which will become the release version shortly.
