### ISSUE TITLE
problem in installation

### ISSUE THREAD

**Issue by ariasamin** [SionBayliss/PIRATE#82]
Dear Sion,
I am highly interested in PIRATE, however I fail in installation every time. 
I am wondering if you or anyone else have ever faced such a problem.
Thank you!!
Narges

**Come on: You have run parallel 109 times. Isn't it about time 
you run 'parallel --citation' once to silence the citation notice?

ERROR: extract_feature_sequences.pl failed
ERROR: PIRATE did not run correctly:
ERROR: PIRATE was not able to extract sequences from GFFS
ERROR: PIRATE was not able to construct pangenome
ERROR: PIRATE was not able to classify paralogs
ERROR: PIRATE could not make summary files

WARNING: PIRATE could not make binary tree (is fasttree installed)
WARNING: PIRATE could not make R plots (are dependencies installed)

tests completed**

**Comment by ariasamin** [comment]
Hi Sion
I am trying to install PIRATE on Linux server, using conda. I also tried "conda install -c sionbayliss pirate".
The report is from "PIRATE --check".

(pirate-env) [narges@node1982 ~]$ PIRATE --check

Running PIRATE on test files:
Academic tradition requires you to cite works you base your article on.
If you use programs that use GNU Parallel to process data for an article in a
scientific publication, please cite:

  Tange, O. (2022, May 22). GNU Parallel 20220522 ('NATO').
  Zenodo. https://doi.org/10.5281/zenodo.6570228

This helps funding further development; AND IT WON'T COST YOU A CENT.
If you pay 10000 EUR you should feel free to use GNU Parallel without citing.

More about funding GNU Parallel and the citation notice:
https://www.gnu.org/software/parallel/parallel_design.html#citation-notice

To silence this citation notice: run 'parallel --citation' once.

Come on: You have run parallel 122 times. Isn't it about time 
you run 'parallel --citation' once to silence the citation notice?

Academic tradition requires you to cite works you base your article on.
If you use programs that use GNU Parallel to process data for an article in a
scientific publication, please cite:

  Tange, O. (2022, May 22). GNU Parallel 20220522 ('NATO').
  Zenodo. https://doi.org/10.5281/zenodo.6570228

This helps funding further development; AND IT WON'T COST YOU A CENT.
If you pay 10000 EUR you should feel free to use GNU Parallel without citing.

More about funding GNU Parallel and the citation notice:
https://www.gnu.org/software/parallel/parallel_design.html#citation-notice

To silence this citation notice: run 'parallel --citation' once.

Come on: You have run parallel 123 times. Isn't it about time 
you run 'parallel --citation' once to silence the citation notice?

Academic tradition requires you to cite works you base your article on.
If you use programs that use GNU Parallel to process data for an article in a
scientific publication, please cite:

  Tange, O. (2022, May 22). GNU Parallel 20220522 ('NATO').
  Zenodo. https://doi.org/10.5281/zenodo.6570228

This helps funding further development; AND IT WON'T COST YOU A CENT.
If you pay 10000 EUR you should feel free to use GNU Parallel without citing.

More about funding GNU Parallel and the citation notice:
https://www.gnu.org/software/parallel/parallel_design.html#citation-notice

To silence this citation notice: run 'parallel --citation' once.

Come on: You have run parallel 124 times. Isn't it about time 
you run 'parallel --citation' once to silence the citation notice?

 - ERROR: extract_feature_sequences.pl failed
 - ERROR: PIRATE did not run correctly:
 - ERROR: PIRATE was not able to extract sequences from GFFS
 - ERROR: PIRATE was not able to construct pangenome
 - ERROR: PIRATE was not able to classify paralogs
 - ERROR: PIRATE could not make summary files

 - WARNING: PIRATE could not make binary tree (is fasttree installed)
 - WARNING: PIRATE could not make R plots (are dependencies installed)

 - tests completed

 - temporary files saved to /local_scratch/pbs.5268374.pbs02/Td2byPuwT5

**Comment by nmc97** [comment]
hello hello :) I'm having the same problem. 

I think at the moment it's to do with upgrading to `BioPerl 1.7+`. `use Bio::Perl` doesn't work with `BioPerl 1.7+` as far as I can tell. Conda won't allow me to downgrade `perl-bioperl`, the newest pirate seems to require it.

`extract_feature_sequences.pl` uses `use Bio::Perl`. I'm trying to work out what to replace it with at the moment. I'll update if I work it out but I'm not familiar enough with Bioperl yet.

Hope this helps a bit,
Nicola.

**Comment by nmc97** [comment]
By `BioPerl 1.7+` I mean `perl-bioperl >= 1.7`

https://github.com/bioperl/bioperl-live/blob/master/HACKING.md#17-releases

**Comment by SionBayliss** [comment]
Hi Both, 

I have updated extract_feature_sequences to reflect the new bioperl package layout. It works on test data and some of my dummy projects. If you use the most up-to-date master branch (git pull) and let me know if it works for you that would be much appreciated. 

All the best,
Sion

**Comment by nmc97** [comment]
Hi Sion,

That worked for me, thank you!

Many thanks,
Nicola.

**Comment by ariasamin** [comment]
Dear Sion, 

I appreciate your help; however, the problem is still there. 

All the best, 
Narges

**Comment by SionBayliss** [comment]
Hi Narges, 

It doesn't look like the new release has made it to conda yet (I don't know what the schedule for that is). So you will need to clone this repo using git:

```
git clone https://github.com/SionBayliss/PIRATE.git
```

And then point to the local files for PIRATE to run commands:

```
/path/to/local/directory/PIRATE -i input -o output etc....
``` 

All the best,
Sion

**Comment by ariasamin** [comment]
Dear Sion,
The error was finally resolved.  Thank you for your support.
-Narges
