### ISSUE TITLE
Bump version in new release

### ISSUE THREAD

**Issue by rpetit3** [SionBayliss/PIRATE#83]
Hi @SionBayliss 

Saw the new release over on Bioconda. Looks like the version bump in `PIRATE` was missed. (https://github.com/SionBayliss/PIRATE/blob/master/bin/PIRATE#L13) (_I do it all the time!_)

Want to get it fixed on this end, or for me to temporarily patch the Bioconda release?

Cheers,
Robert

**Comment by SionBayliss** [comment]
Hi @rpetit3,

Happy to fix it this end. What would I need to do?

All the best,
Sion

**Comment by rpetit3** [comment]
Either a release of v1.0.5 with the correction, or a new v1.0.6 release with the correction. Either works for me and the bot should pick it up

**Comment by SionBayliss** [comment]
This *should* be resolved now :)

**Comment by rpetit3** [comment]
Sure did! https://github.com/bioconda/bioconda-recipes/pull/35649

Thank you!
