### ISSUE TITLE
understanding pirate results 

### ISSUE THREAD

**Issue by happymanmohit** [SionBayliss/PIRATE#88]
Hii 
               I ran a pangenome analysis for 7 genomes using bacteria, which used Pirate for the pangenome analysis and gave results as pirate unique alleles, gene presence_absence. Now, it is very hard for me to understand the output. Can you please suggest how to find which genes are absent or present in a particular genome?

**Comment by SionBayliss** [comment]
Hi Mohit, 

The description of the output formats can be found in the README under the 'PIRATE.*.tsv file format' section. There is a series of columns at the end of each file which correspond to your input genomes. The gene_presence_absence file is the one you should be looking at. 

S
