### ISSUE TITLE
question on presente/absence gene table data

### ISSUE THREAD

**Issue by jianshu93** [SionBayliss/PIRATE#89]
Dear Team,

I have the attached plot for a pan genome analysis. what output data this plot was based on and how can I extract the information of each gene (including representative sequences).
[SAR11_IIa.A_pangenome_cluster.pdf](https://github.com/user-attachments/files/16255769/SAR11_IIa.A_pangenome_cluster.pdf)

Thanks,

Jianshu

**Comment by SionBayliss** [comment]
Hi Jian, 

The 'PIRATE.gene_presence_absence.tsv' table contains all of the information used to create the output figures. There are some support scripts to identify subsets of the table should you need it. 

All the best,
Sion
