### ISSUE TITLE
possible bug with unlinking files

### ISSUE THREAD

**Issue by tseemann** [SionBayliss/PIRATE#9]
```
        # remove previous test files.
        unlink "$output_dir/modified_gffs/HO_5096_0412_test.gff" if "$output_dir/modifi
ed_gffs/HO_5096_0412_test.gff";
```

did you mean `if -f "$output/..."` or `-e` ?
because the string will always be true, you want to test the file?

**Comment by SionBayliss** [comment]
--check now writes to a temp directory so these lines have been removed.
